# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /afs/inf.ed.ac.uk/user/s19/s1902743/Desktop/Work/computer-architecture-practical/Practical-1d/prac1d/src/constraints/top.xdc

# XDC: /afs/inf.ed.ac.uk/user/s19/s1902743/Desktop/Work/computer-architecture-practical/Practical-1d/prac1d/src/constraints/timing.xdc

# IP: /afs/inf.ed.ac.uk/user/s19/s1902743/Desktop/Work/computer-architecture-practical/Practical-1d/prac1d/src/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] -quiet

# IP: /afs/inf.ed.ac.uk/user/s19/s1902743/Desktop/Work/computer-architecture-practical/Practical-1d/prac1d/src/ip/video_clock_gen/video_clock_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_clock_gen || ORIG_REF_NAME==video_clock_gen} -quiet] -quiet

# IP: /afs/inf.ed.ac.uk/user/s19/s1902743/Desktop/Work/computer-architecture-practical/Practical-1d/prac1d/src/ip/cpu_clock_gen/cpu_clock_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_clock_gen || ORIG_REF_NAME==cpu_clock_gen} -quiet] -quiet
